/**
 * Report Routes
 * Generates a downloadable PDF accessibility report using PDFKit
 */

const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');

/**
 * POST /api/report/generate
 * Body: { analysis: {...}, filename: 'design.png' }
 * Returns a PDF file stream
 */
router.post('/generate', (req, res) => {
  const { analysis, filename } = req.body;

  if (!analysis) {
    return res.status(400).json({ error: 'Analysis data is required' });
  }

  try {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="accessibility-report.pdf"`);
    doc.pipe(res);

    // ─── Header ─────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 80).fill('#0f172a');
    doc.fillColor('#ffffff')
       .fontSize(22)
       .font('Helvetica-Bold')
       .text('Accessibility Design Report', 50, 25);
    doc.fontSize(11)
       .font('Helvetica')
       .text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 50, 52);

    doc.moveDown(3);

    // ─── Score Section ───────────────────────────────────────────
    doc.fillColor('#0f172a').fontSize(16).font('Helvetica-Bold').text('Overall Accessibility Score', 50, 100);

    const scoreColor = analysis.score >= 80 ? '#16a34a' : analysis.score >= 50 ? '#d97706' : '#dc2626';
    doc.fillColor(scoreColor).fontSize(48).font('Helvetica-Bold').text(`${analysis.score}/100`, 50, 122);

    doc.fillColor('#64748b').fontSize(11).font('Helvetica')
       .text(`File analyzed: ${filename || 'Unknown'}`, 50, 178)
       .text(`Total issues found: ${analysis.totalIssues}`, 50, 194)
       .text(`High severity: ${analysis.severityCounts?.high || 0}   Medium: ${analysis.severityCounts?.medium || 0}   Low: ${analysis.severityCounts?.low || 0}`, 50, 210);

    doc.moveDown(2);
    drawDivider(doc, 230);

    // ─── Issues List ─────────────────────────────────────────────
    doc.fillColor('#0f172a').fontSize(16).font('Helvetica-Bold').text('Detected Issues', 50, 250);

    let y = 275;
    (analysis.issues || []).forEach((issue, i) => {
      if (y > 720) { doc.addPage(); y = 50; }

      const sevColor = issue.severity === 'high' ? '#dc2626' : issue.severity === 'medium' ? '#d97706' : '#2563eb';
      doc.fillColor(sevColor).fontSize(10).font('Helvetica-Bold')
         .text(`[${issue.severity?.toUpperCase()}] ${issue.type}`, 50, y);
      y += 16;

      doc.fillColor('#374151').fontSize(10).font('Helvetica')
         .text(issue.description, 50, y, { width: 495 });
      y += 28;

      doc.fillColor('#059669').fontSize(9).font('Helvetica-Oblique')
         .text(`Fix: ${issue.suggestion}`, 60, y, { width: 485 });
      y += 14;

      doc.fillColor('#94a3b8').fontSize(8).font('Helvetica')
         .text(`Reference: ${issue.wcag}`, 60, y);
      y += 24;

      drawDivider(doc, y);
      y += 14;
    });

    // ─── Suggestions ─────────────────────────────────────────────
    if (y > 680) { doc.addPage(); y = 50; }
    y += 10;
    doc.fillColor('#0f172a').fontSize(16).font('Helvetica-Bold').text('Improvement Suggestions', 50, y);
    y += 30;

    (analysis.suggestions || []).forEach((s, i) => {
      if (y > 720) { doc.addPage(); y = 50; }
      doc.fillColor('#1d4ed8').fontSize(11).font('Helvetica-Bold').text(`${i + 1}. ${s.title}`, 50, y);
      y += 16;
      doc.fillColor('#374151').fontSize(10).font('Helvetica')
         .text(s.detail, 60, y, { width: 485 });
      y += 36;
    });

    // ─── Footer ──────────────────────────────────────────────────
    doc.addPage();
    doc.rect(0, doc.page.height - 60, doc.page.width, 60).fill('#f8fafc');
    doc.fillColor('#64748b').fontSize(9).font('Helvetica')
       .text('Generated by Accessibility Design Checker • Powered by WCAG 2.1 Standards', 50, doc.page.height - 40, { align: 'center', width: doc.page.width - 100 });

    doc.end();
  } catch (err) {
    console.error('PDF error:', err);
    res.status(500).json({ error: 'Failed to generate report: ' + err.message });
  }
});

function drawDivider(doc, y) {
  doc.moveTo(50, y).lineTo(545, y).strokeColor('#e2e8f0').lineWidth(1).stroke();
}

module.exports = router;
